version: "3"

services:
  unity-accelerator:
    image: unitytechnologies/accelerator
    ports:
      - '80:80'
    restart: always
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 3m
