version: "3"

services:
  unity-accelerator:
    image: unitytechnologies/accelerator
    ports:
      - '80:80'
      - '443:443'
      - '5678:10080'
      - '10443:10443'
    volumes:
      - accelerator-volume:/agent
    env_file:
      - ./.env
    restart: always
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 3m

volumes:
  accelerator-volume:
    driver: "local"