version: "3"

services:
  unity-accelerator:
    image: unitytechnologies/accelerator
    ports:
      - '80:80'
      - '443:443'
      - '10080:10080'
    volumes:
      - ./agent:/agent/
    env_file:
      - ./.env
    restart: always
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 3m
